
    
cp ProjectBochumGaborFiltersResults.png $HOME
cp ProjectBristol_1_0.png $HOME
cp ProjectChrisWiley_1_0.png $HOME
cp ProjectCrossPoll3.png $HOME
cp ProjectGtst_1_2.png $HOME
cp ProjectMuscaDomestica_1_0.png $HOME
cp ProjectThorVeen_0_9.png $HOME
cp ProjectWtWebsiteBep.png $HOME
cp ProjectRichelBilderbeek_1_14.png $HOME
    



    
cp GameAminoAcidFighter_0_9.png $HOME
cp GameAthleticLand_0_9.png $HOME
cp GameBeerWanter3.png $HOME
cp GameBeerWanter5.png $HOME
cp GameBoenken_1_0.png $HOME
cp GameBoenken_3_1.png $HOME
cp GameBoenken_4_1.png $HOME
cp GameConnectThree_5_2.png $HOME
cp GameConnectThree_6_0.png $HOME
cp GameCorridor.png $HOME
cp GameDasWahreSchlagerfest_1_0.png $HOME
cp GameDasWahreSchlagerfest_2_0.png $HOME
cp GameDasWahreSchlagerfest_2_2.png $HOME
cp GameK3OpEenRij_4_0.png $HOME
cp GameK3OpEenRij_5_0.png $HOME
cp GameK3OpEenRij_6_0.png $HOME
cp GameKnokfighter_1_0.png $HOME
cp GameMartianCafeTuinemaTycoon_1_0.png $HOME
cp GameMaziak_1_3.png $HOME
cp GameMaziak_2_0.png $HOME
cp GameMetZnDrieen_1_3.png $HOME
cp GamePokeVolley_2_0.png $HOME
cp GamePylos_1_0.png $HOME
cp GameReversiConsole_1_0.png $HOME
cp GameRubiksClock_1_0.png $HOME
cp GameRubiksClock_2_1.png $HOME
cp GameRubiksClockDesktop_2_2.png $HOME
cp GameSearchAndDestroyChess_1_0.png $HOME
cp GameSearchAndDestroyChess_2_0.png $HOME
cp GameSearchAndDestroyChessConsole_1_0.png $HOME
cp GameSimPredator_1_0.png $HOME
cp GameSpaceHarry_1_0.png $HOME
cp GameTicTacToe_1_1.png $HOME
cp GameTicTacToe_1_2.png $HOME
cp GameTicTacToe_1_4.png $HOME
cp GameXeNonZero_0_1.png $HOME
cp GameZork.png $HOME
cp GameTicTacToe_1_6.png $HOME
cp GameTicTacToe_1_5.png $HOME
cp GameDasWahreSchlagerfest_2_5.png $HOME
cp GameRubiksClock_2_3.png $HOME
cp GameReversiVcl_1_0.png $HOME
cp GameReversi_0_1.png $HOME
cp GamePylos_2_1.png $HOME
    


    
cp ToolTestToggleButton_1_4.png $HOME
cp ToolTestTwoDigitNewick_2_2.png $HOME
cp ToolTestTextPositionWidget_1_4.png $HOME
cp ToolTestTextCanvas_1_0.png $HOME
cp ToolTestSimpleLinearRegression_1_2.png $HOME
cp ToolTestShinyButton_2_1.png $HOME
cp ToolTestShape_2_1.png $HOME
cp ToolTestReversi_0_1.png $HOME
cp ToolTestQtRoundedTextRectItem_1_2.png $HOME
cp ToolTestQuestion_3_1.png $HOME
cp ToolTestQtRoundedRectItem_1_2.png $HOME
cp ToolTestQtRoundedEditRectItem_1_2.png $HOME
cp ToolTestQtHideAndShowDialog_0_1.png $HOME
cp ToolTestKeyboardFriendlyGraphicsView_0_4.png $HOME
cp ToolTestQtModels_1_2.png $HOME
cp ToolTestQtCreatorProFile_1_4.png $HOME
cp ToolTestQrcFile_1_3.png $HOME
cp ToolTestOpenQuestion_1_0.png $HOME
cp ToolTestPlane_1_0.png $HOME
cp ToolTestNewickVector_3_2.png $HOME
cp ToolTestMultipleChoiceQuestionDialog_1_0.png $HOME
cp ToolTestManyDigitNewick_1_0.png $HOME
cp ToolTestMultiCanvas_1_0.png $HOME
cp ToolTestGraphicsProxyWidget_0_1.png $HOME
cp ToolTestImageCanvas_1_0.png $HOME
cp ToolTestGravityWidget_0_1.png $HOME
cp ToolTestConceptMap_1_0.png $HOME
cp ToolTestDial_2_3.png $HOME
cp ToolTestDrawCanvas_1_2.png $HOME
cp ToolTriangleMeshCreator_1_2.png $HOME
cp ToolTestPlane_1_1.png $HOME
cp ToolWktToSvg_1_3.png $HOME
    


    
cp CppGnuplotInterface.png $HOME
cp PicBlack.png $HOME
cp PicCl.png $HOME
cp PicDesktop.png $HOME
cp PicGreen.png $HOME
cp PicLinux.png $HOME
cp PicMac.png $HOME
cp PicOrange.png $HOME
cp PicR.png $HOME
cp PicRed.png $HOME
cp PicWeb.png $HOME
cp PicWindows.png $HOME
cp PicYellow.png $HOME
cp RichelbilderbeekNlBackground.png $HOME
    



    
cp ToolAsciiArter_1_0.png $HOME
cp ToolAsciiArter_5_0.png $HOME
cp ToolAsciiArter_5_1.png $HOME
cp ToolBarbaImage_1_3.png $HOME
cp ToolCodeToHtml_1_13.png $HOME
cp ToolCodeToHtml_2_0.png $HOME
cp ToolCodeToHtml_2_3.png $HOME
cp ToolCreateQtProjectZipFile_1_3.png $HOME
cp ToolCreateQtProjectZipFile_2_0.png $HOME
cp ToolDotMatrix_1_0.png $HOME
cp ToolEncranger_1_0.png $HOME
cp ToolEncranger_2_1.png $HOME
cp ToolEncranger_2_5.png $HOME
cp ToolFilterOperationer_1_0.png $HOME
cp ToolFryskLeareLieder_1_0.png $HOME
cp ToolFunctionPlotter_1_1.png $HOME
cp ToolGaborFilter_1_0.png $HOME
cp ToolGaborFilter_2_0.png $HOME
cp ToolGrayCoder_1_0.png $HOME
cp ToolGrayCoder_2_1.png $HOME
cp ToolHistogramEqualizationer_1_0.png $HOME
cp ToolHometrainer_1_8.png $HOME
cp ToolHometrainer_2_0.png $HOME
cp ToolImageRotaterClx_1_0.png $HOME
cp ToolImageRotaterVcl_1_0.png $HOME
cp ToolKalmanFilterer_1_11.png $HOME
cp ToolKalmanFilterer_1_4.png $HOME
cp ToolKalmanFilterer_1_5.png $HOME
cp ToolKalmanFilterer_1_6.png $HOME
cp ToolKeySender_1_0.png $HOME
cp ToolLearyCircumplex_1_0.png $HOME
cp ToolLogisticGrowthSimulator_1_0.png $HOME
cp ToolLoose_2_0.png $HOME
cp ToolMazeCreator_1_0.png $HOME
cp ToolMazeCreator_2_0.png $HOME
cp ToolMorpher_1_0.png $HOME
cp ToolMultiEncranger_1_0.png $HOME
cp ToolMusicTheory_1_0.png $HOME
cp ToolNdsmakeUse_1_0.png $HOME
cp ToolPaperRockScissors_1_0.png $HOME
cp ToolPerfectElasticCollision_1_0.png $HOME
cp ToolPicToCode_1_2.png $HOME
cp ToolPicToCode_1_3.png $HOME
cp ToolPixelator_1_0.png $HOME
cp ToolQuadraticSolver_1_0.png $HOME
cp ToolRandomCode_1_0.png $HOME
cp ToolRandomCode_2_0.png $HOME
cp ToolRandomCode_2_1.png $HOME
cp ToolRandomCode_3_0.png $HOME
cp ToolRandomCode_4_2.png $HOME
cp ToolRasper_0_3.png $HOME
cp ToolRefrigeratorPuzzleSolver_1_0.png $HOME
cp ToolRegexTester_1_0.png $HOME
cp ToolRegexTester_1_1.png $HOME
cp ToolRichelBilderbeekGallery_1_0.png $HOME
cp ToolRichelbilderbeekNlSitemapGenerator_2_0.png $HOME
cp ToolSecretMessage_1_0.png $HOME
cp ToolSimBrainiac_1_0.png $HOME
cp ToolSimImmuneResponse_1_0.png $HOME
cp ToolSimMysteryMachine_1_1_desktop.png $HOME
cp ToolSimMysteryMachine_1_1_web.png $HOME
cp ToolSimMysteryMachine_1_2.png $HOME
cp ToolSimplifyNewick_1_2.png $HOME
cp ToolSimStagecraft_1_1.png $HOME
cp ToolSoaSim_1_0.png $HOME
cp ToolStateObserver_1_0.png $HOME
cp ToolSurfacePlotter_1_0.png $HOME
cp ToolSurfacePlotter_1_1.png $HOME
cp ToolSurfacePlotter_1_2.png $HOME
cp ToolSurfacePlotter_2_0.png $HOME
cp ToolTestAbout_1_1.png $HOME
cp ToolTestApproximator_1_0.png $HOME
cp ToolTestAsciiArter.htm $HOME
cp ToolTestAsciiArter_1_0.png $HOME
cp ToolTestAsciiArter_4_0.png $HOME
cp ToolTestAsciiArter_4_1.png $HOME
cp ToolTestBinaryNewickVector_1_5.png $HOME
cp ToolTestBouncingBallsWidget_1_0.png $HOME
cp ToolTestBouncingRectsWidget_1_0.png $HOME
cp ToolTestBroadcastServer_1_0.png $HOME
cp ToolTestChess20120207.png $HOME
cp ToolTestChess20120209.png $HOME
cp ToolTestDial_1_0.png $HOME
cp ToolTestDial_1_1.png $HOME
cp ToolTestEntrance_1_0.png $HOME
cp ToolTestExercise_1_0.png $HOME
cp ToolTestFunctionParser_1_0.png $HOME
cp ToolTestFunctionParser_2_0.png $HOME
cp ToolTestFunctionParser_2_1.png $HOME
cp ToolTestGroupWidget_1_0.png $HOME
cp ToolTestLed_1_0.png $HOME
cp ToolTestLed_1_1.png $HOME
cp ToolTestMultiApproximator_1_0.png $HOME
cp ToolTestNdsmake_1_0.png $HOME
cp ToolTestNeuralNet_0_1.png $HOME
cp ToolTestPrimeExpert_1_0.png $HOME
cp ToolTestPylos_1_0.png $HOME
cp ToolTestQtArrowItems_1_0.png $HOME
cp ToolTestQtRoundedEditRectItem_1_0.png $HOME
cp ToolTestQtRoundedRectItem_1_1.png $HOME
cp ToolTestQtRoundedTextRectItem_1_1.png $HOME
cp ToolTestQuestion_0_9.png $HOME
cp ToolTestQuestion_1_0.png $HOME
cp ToolTestQuestion_2_1.png $HOME
cp ToolTestSelectFileDialog_1_1.png $HOME
cp ToolTestShape_1_0_desktop.png $HOME
cp ToolTestShape_1_0_web.png $HOME
cp ToolTestShinyButton_2_0_desktop.png $HOME
cp ToolTestShinyButton_2_0_web.png $HOME
cp ToolTestSimpleLinearRegression_1_0.png $HOME
cp ToolTestTicTacToe_1_1.png $HOME
cp ToolTestTicTacToe_1_2.png $HOME
cp ToolTestTwoDigitNewick_0_6.png $HOME
cp ToolThresholdFilterer_1_0.png $HOME
cp ToolTicTacToeLearner_0_3.png $HOME
cp ToolTicTacToeValuer_0_7.png $HOME
cp ToolTimePoll_4_1.png $HOME
cp ToolUbuntuOneWatcher_1_0.png $HOME
cp ToolVisualAbc_1_0.png $HOME
cp ToolPrimeExpert_2_1.png $HOME
cp ToolImageRotater_2_0.png $HOME
cp ToolHistogramEqualizationer_2_0.png $HOME
cp ToolDotMatrix_2_0.png $HOME
cp ToolDotMatrix_2_1.png $HOME
cp ToolFilterOperationer_2_0.png $HOME
cp ToolFunctionPlotter_2_0.png $HOME
cp ToolCreateGlossary_1_2.png $HOME
cp ToolAsciiArter_5_2.png $HOME
cp ToolCodeToHtml_3_1.png $HOME
cp ToolCaesarCipher_1_0.png $HOME
cp ToolAsciiArter_6_0.png $HOME
cp ToolQmakeWatcher_1_0.png $HOME
cp ToolPreDickAdvocaTor_2_1.png $HOME
cp ToolPreDickAdvocaTor_1_0.png $HOME
cp ToolTriangleMeshCreator_1_2.png $HOME
cp ToolKalmanFilterer_1_15.png $HOME
cp ToolMultiEncranger_2_3.png $HOME
cp ToolQuadraticSolver_2_1.png $HOME
cp ToolSecretMessage_2_1.png $HOME
cp ToolTestTriangle_1_1.png $HOME
cp ToolThresholdFilterer_2_0.png $HOME
cp ToolValentineCardDecrypter_2_0.png $HOME
cp ToolValentineCardDecrypter_2_0_Windows.png $HOME
cp ToolVigenereCipher_1_0.png $HOME
cp ToolWktToSvg_1_0.png $HOME
cp ToolWktToSvg_1_1.png $HOME
    

